-- 몰입 아카데미 최초 스키마.
--
-- 이 파일은 손으로 쓴 것이 아니라 Hibernate가 PostgreSQLDialect로 생성한 DDL을 옮긴 것이다.
-- 운영 프로파일이 ddl-auto: validate로 뜨므로, 엔티티와 어긋나면 앱이 아예 기동하지 않는다.

CREATE TABLE member (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR(20)  NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    nickname    VARCHAR(20)  NOT NULL UNIQUE,
    create_date TIMESTAMP(6),
    modify_date TIMESTAMP(6),
    PRIMARY KEY (id)
);

CREATE TABLE refresh_token (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    token       VARCHAR(512) NOT NULL UNIQUE,
    member_id   BIGINT       NOT NULL,
    expires_at  TIMESTAMP(6) NOT NULL,
    create_date TIMESTAMP(6),
    modify_date TIMESTAMP(6),
    PRIMARY KEY (id)
);

-- (회원, 일지 날짜)의 unique 제약이 이 도메인의 핵심이다. 날짜로 일지를 지목하는
-- API 형태(ADR 0002)가 이 제약 위에 서 있다.
CREATE TABLE journal (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id            BIGINT  NOT NULL,
    journal_date         DATE    NOT NULL,
    sleep_minutes        INTEGER,
    study_minutes        INTEGER,
    exercise_minutes     INTEGER,
    nap_count            INTEGER,
    one_second_rule_rate NUMERIC(4, 1),
    mood                 VARCHAR(20) CHECK (mood IN ('VERY_GOOD', 'GOOD', 'NORMAL', 'BAD', 'VERY_BAD')),
    slow_thinking        BOOLEAN,
    thought_before_sleep BOOLEAN,
    vitamin_taken        BOOLEAN,
    content              TEXT,
    create_date          TIMESTAMP(6),
    modify_date          TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_journal_member_date UNIQUE (member_id, journal_date)
);

ALTER TABLE journal
    ADD CONSTRAINT fk_journal_member FOREIGN KEY (member_id) REFERENCES member;

ALTER TABLE refresh_token
    ADD CONSTRAINT fk_refresh_token_member FOREIGN KEY (member_id) REFERENCES member;

-- 목록 화면이 (회원, 기간)으로 조회하므로 unique 제약 인덱스가 그대로 쓰인다.
-- 로그아웃과 재발급은 토큰 값으로 찾으므로 unique 인덱스가 역할을 한다.
